#!/bin/bash

dir=${PWD##*/}

if [[ ${dir} == "build" ]]
then
  read -r -n 1 -p "Deleting everything in ${PWD}. Are you sure? [y/N] " input
  if [[ "${input}" =~ [yY] ]]
  then
    printf "\nCleaning build directory"
    rm -rf ./*
  fi
else
  printf "Not in build directory, exiting"
fi
