#!/bin/bash

dir=${PWD##*/}

if [[ ${dir} == "build" ]]
then
  read -r -p "Deleting everything in ${PWD}. Are you sure? [y/N] " input
  if [[ "${input}" =~ [yY] ]]
  then
    echo "Cleaning build directory"
    rm -rf ./*
  fi
else
  echo "Not in build directory, exiting"
fi
