#!/bin/bash

temp=`sensors | grep -e 'CPU:.*°C' | awk '{print $2}'`
temp=${temp:1:2}

# Set the icon and deafult colour
icon="^i(/home/robin/scripts/icons/temp.xbm)"
color="^fg()"

# Change colour depending on temperature
if [[ $temp -ge 80 ]]; then
    color="^fg(#cc0000)"
elif [[ $temp -ge 70 ]]; then
    color="^fg(#aa5500)"
elif [[ $temp -ge 60 ]]; then
    color="^fg(#aaaa00)"
fi

# Output
echo "$icon $color$temp°C"
