#!/bin/bash

# WIFI ICONS
# îƒ±îƒ®îƒ²îƒ¯îƒ³îƒ°

QUAL=`iwconfig wlp12s0 | grep 'Link Quality=' | awk '{gsub(/[=/]/," "); print $3}'`
MAX=`iwconfig wlp12s0 | grep 'Link Quality=' | awk '{gsub(/[=/]/," "); print $4}'`
PERC=`echo $QUAL*100/$MAX | bc`

icon=""
case $PERC in
   100)
      icon="^i(/home/robin/scripts/icons/wifi_100.xbm)"
   ;;
   [0-1]*)
      icon="^i(/home/robin/scripts/icons/wifi_0.xbm)"
   ;;
   [2-3]*)
      icon="^i(/home/robin/scripts/icons/wifi_20.xbm)"
   ;;
   [4-5]*)
      icon="^i(/home/robin/scripts/icons/wifi_40.xbm)"
   ;;
   [6-7]*)
      icon="^i(/home/robin/scripts/icons/wifi_60.xbm)"
   ;;
   [8]*)
      icon="^i(/home/robin/scripts/icons/wifi_80.xbm)"
   ;;
   [9]*)
      icon="^i(/home/robin/scripts/icons/wifi_100.xbm)"
   ;;
   *)
      icon="^fg(#cc0000)^i(/home/robin/scripts/icons/error.xbm)"
   ;;
esac

echo "$icon"

