#!/bin/sh

#echo -n $(uptime | sed 's/.*://; s/,//g')
load=$(uptime | sed -e "s/.*load average: \(.*\...\), \(.*\...\), \(.*\...\)/\1/" -e "s/ //g")
load=${load:2}
load=$(($load/2))
echo -n "$load\%"
