#!/bin/bash

VOL=`amixer get Master | awk 'FNR == 5 {print $4}' | tr -d '[]%'`
MUTE=`amixer get Master | awk 'FNR == 5 {print $6}' | tr -d '[]'`

icon=""

bar=""
case $VOL in
	100)
		bar="---------"
		;;
	0)
		bar="\f8---------"
      icon=""
		;;
	[1-5])
		bar="\f8---------"
		;;
	[5-9])
		bar="-\f8--------"
		;;
	[1-2]*)
		bar="--\f8-------"
		;;
	3*)
		bar="---\f8------"
		;;
	4*)
		bar="----\f8-----"
		;;
	5*)
		bar="-----\f8----"
		;;
	6*)
		bar="------\f8---"
		;;
	7*)
		bar="-------\f8--"
		;;
	8*)
		bar="--------\f8-"
		;;
	*)
		bar="---------"
		;;
esac

if [[ $MUTE = "off" ]]; then
	icon="\f1$icon"
else
	icon="\f $icon"
fi

echo "$icon \f9$bar"
