#!/bin/bash

BAT=`acpi -b | awk '{gsub(/%,/,""); print $4}' | sed 's/%//g'`
STATUS=`acpi -b | awk '{gsub(/,/,""); print $3}'`

icon=""
if [[ $BAT -lt 10 ]]; then
	icon="^i(/home/robin/scripts/icons/bat_0.xbm)"
elif [[ $BAT -lt 20 ]]; then
	icon="^i(/home/robin/scripts/icons/bat_1.xbm)"
elif [[ $BAT -lt 40 ]]; then
	icon="^i(/home/robin/scripts/icons/bat_2.xbm)"
elif [[ $BAT -lt 60 ]]; then
	icon="^i(/home/robin/scripts/icons/bat_3.xbm)"
elif [[ $BAT -lt 80 ]]; then
	icon="^i(/home/robin/scripts/icons/bat_4.xbm)"
elif [[ $BAT -lt 100 ]]; then
	icon="^i(/home/robin/scripts/icons/bat_5.xbm)"
elif [[ $BAT = 100 ]]; then
	icon="^i(/home/robin/scripts/icons/bat_6.xbm)"
else
   icon=""
fi
if [[ $STATUS != "Discharging" ]]; then
   icon="^i(/home/robin/scripts/icons/ac.xbm)$icon"
fi

bar=""
case $BAT in
   100)
      bar="^fg(#00aa00)$BAT"
      ;;
   [0-9])
      bar="^fg(#ff0000)$BAT"
      ;;
   [5-9]*)
      bar="^fg(#00aa00)$BAT"
      ;;
   [2-5]*)
      bar="^fg(#cccc00)$BAT"
      ;;
   [1-2]*)
      bar="^fg(#cc6600)$BAT"
      ;;
   *)
      bar="^fg(#ff0000)$BAT"
      ;;
esac

echo "$icon $bar%"
