#!/bin/bash

# Current system volume
VOL=`amixer get Master | awk 'FNR == 6 {print $4}' | tr -d '[]%'`
# Current mute status
MUTE=`amixer get Master | awk 'FNR == 6 {print $6}' | tr -d '[]'`

# Deafult icon
icon="^i(/home/robin/scripts/icons/vol_100.xbm)"

# Colours for the volume bar
fullcolor="^fg(#cc6666)"
emptycolor="^fg(#425059)"

# Show bar depending on volume
bar=""
case $VOL in
	100)
		bar="---------"
		;;
	0)
		bar="$emptycolor---------"
		;;
	[1-5])
		bar="$emptycolor---------"
		;;
	[5-9])
		bar="-$emptycolor--------"
		;;
	[1-2]*)
		bar="--$emptycolor-------"
		;;
	3*)
		bar="---$emptycolor------"
		;;
	4*)
		bar="----$emptycolor-----"
		;;
	5*)
		bar="-----$emptycolor----"
		;;
	6*)
		bar="------$emptycolor---"
		;;
	7*)
		bar="-------$emptycolor--"
		;;
	8*)
		bar="--------$emptycolor-"
		;;
	*)
		bar="---------"
		;;
esac

# Change icon depending on volume
if [[ $VOL = 0 ]]; then
	icon="^i(/home/robin/scripts/icons/vol_0.xbm)"
elif [[ $VOL -lt 50 ]]; then
	icon="^i(/home/robin/scripts/icons/vol_50.xbm)"
else
	icon="^i(/home/robin/scripts/icons/vol_100.xbm)"
fi

# Change colour of icon depending on volume
if [[ $MUTE = "off" ]]; then
	icon="^fg(#cc0000)$icon"
else
	icon="^fg()$icon"
fi

# Output
echo "$icon $fullcolor$bar"
