#!/bin/bash

VOL=`amixer get Master | awk 'FNR == 5 {print $4}' | tr -d '[]%'`
MUTE=`amixer get Master | awk 'FNR == 5 {print $6}' | tr -d '[]'`

#icon=""
#if [[ $VOL -lt 1 ]]; then
#	icon=""
#else
#	icon=""
#fi

bar=""
vol="V"
case $VOL in
	100)
		bar="---------"
		;;
	[0-5])
		bar="\f8---------"
		;;
	[5-9])
		bar="\f3-\f8--------"
		;;
	[1-2]*)
		bar="--\f8-------"
		;;
	3*)
		bar="---\f8------"
		;;
	4*)
		bar="----\f8-----"
		;;
	5*)
		bar="-----\f8----"
		;;
	6*)
		bar="------\f8---"
		;;
	7*)
		bar="-------\f8--"
		;;
	8*)
		bar="--------\f8-"
		;;
	*)
		bar="---------"
		;;
esac
case $MUTE in
   on)
      vol="\f V "
      ;;
   off)
      vol="\f1V "
      ;;
esac

echo "$icon $vol\f9$bar"
