#!/bin/bash

CPU1=`sensors | awk 'FNR == 3 {print $3}' | tr -d '.+°C'`
CPU2=`sensors | awk 'FNR == 4 {print $3}' | tr -d '.+°C'`

icon="^i(/home/robin/scripts/icons/temp.xbm)"
color="^fg()"
temp="$(((($CPU1/10)+($CPU2/10))/2))"

if (($temp >= 60)); then
   color="^fg(#aaaa00)"
elif (($temp >= 70)); then
   color="^fg(#aa5500)"
elif (($temp >= 80)); then
   color="^fg(#cc0000)"
fi

echo "$icon $color$temp°C"
