#
# ~/.zshrc

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

# Vim mode
set -o vi

# Avoid successive duplicate commands in history
setopt HIST_IGNORE_DUPS

# Feel good alias for sudo
alias fucking='sudo'

# Dir listings
alias ls='ls --color=auto'
alias la='ls -A'
alias ll='ls -lA'

# Ease of use
alias cd..='cd ..'
alias y='yaourt'

# Git
alias gs='git status'
alias gc='git commit'
alias gac='git commit -a'
alias ga='git add'
alias gd='git diff'
alias gph='git push'
alias gpl='git pull'

function zle-line-init zle-keymap-select {
    PROMPT="[%2~] ${${KEYMAP/vicmd/--NORMAL--}/(main|viins)/--INSERT--}
 >> "
    zle reset-prompt
}
zle -N zle-line-init
zle -N zle-keymap-select

